package commonMethods;

public interface OR {

	
	 
	 
	 public static String burrowLogo="BurrowLogo>.//i[@class='icon icon-burrow']";
	 public static String shopSofas="ShopsofasButton>.//a[text()='Shop Sofas']";
	 public static String sofa="LoveSeatSofa>.//h5[text()='Loveseat']";
	 public static String armChair="ArmChair>.//h5[text()='Armchair']";
	 public static String ottoman="Ottoman>.//h5[text()='Ottoman']";
	 public static String kingSofa="KingSofa>.//h5[text()='King Sofa']";
	 public static String addToBox="AddToBoxButton>.//p[text()='Add To Box']";
	 public static String yourBox="YourBoxPopup>.//h2[text()='Your box']";
	 public static String cartSofa="SofaCart>.//div[text()='Loveseat']";
	 public static String cartArmChair="ArmChairInCart>.//div[text()='Armchair']";
	 public static String cartOttoman="OttomanInCart>.//div[text()='Ottoman']";
	 public static String cartKingSofa="KingSofaInCart>.//div[text()='King Sofa']";
	 public static String placeOrderSofa="SofaInPlaceOrder>(.//div[text()='Loveseat'])[2]";
	 public static String placeOrderArmChair="ArmChairInPlaceOrder>(.//div[text()='Armchair'])[2]";
	 public static String placeOrderOttoman="OttomanInPlaceOrder>(.//div[text()='Ottoman'])[2]";
	 public static String placeOrderKingSofa="KingSofaInPlaceOrder>(.//div[text()='King Sofa'])[2]";
	 //public static String placeOrderProduct="ProductInPlaceOrder>(.//div[@class='description'])[3]";
	 public static String cartIcon="CartIcon>.//i[@class='nav-icons icon-cart-empty']";
	 public static String emptyCart="EmptyCart>.//h5[text()='Your box is currently empty']";
	 public static String removeClose="RemoveIcon>(.//i[@class='icon icon-close'])[2]";
	 public static String removeCloseInExtraSet="RemoveIconInExtraSet>(.//i[@class='icon icon-close'])[3]";
	 public static String cartClose="CartCloseButton>(.//i[@class='icon icon-close'])[1]";
	 public static String color1="Color>.//li[@aria-label='with Beige Fabric']";
	 public static String color2="Color>.//li[@aria-label='with Brick Red Fabric']";
	 public static String color3="Color>.//li[@aria-label='with Crushed Gravel Fabric']";
	 public static String color4="Color>.//li[@aria-label='with Navy Blue Fabric']";
	 public static String color5="Color>.//li[@aria-label='with Charcoal Fabric']";
	 public static String legColor1="WoodLegColor>.//li[@aria-label='with Dark Wood Legs']";
	 public static String legColor2="WoodLegColor>.//li[@aria-label='with Light Wood Legs']";
	 public static String legColor3="WoodLegColor>.//li[@aria-label='with Matte Black Legs']";
	 public static String lowArmIcon="LowArmIcon>.//li[@aria-label='with Low Arms']";
	 public static String highArmIcon="HighArmIcon>.//li[@aria-label='with High Arms']";
	 public static String ottomanIcon="OttomanIcon>.//li[@aria-label='With ottoman']";
	 public static String chaiseIcon="ChaiseIcon>.//li[@aria-label='With chaise']";
	 public static String priceInAddToBox="PriceInAddToBox>(.//p[@class='book sandstone'])[1]";
	 public static String chaiseInCart="ChaiseInCart>.//div[@class='description']";
	 public static String colorInCart="ColorInCart>(.//h5[@class='cart-item-info'])[1]";
	 public static String priceInCart="PriceInCart>(.//div[@class='cart-item-price'])[1]";
	 public static String cartSubTotal="SubTotalInCart>(.//span[@class='amount'])[1]";
	 public static String placeOrderSubTotal="SubTotalInPlaceOrder>(.//h6[@class='book up'])[1]";
	 public static String placeOrderTax="TaxInPlaceOrder>(.//h6[@class='book up'])[2]";
	 public static String placeOrderTotal="TotalInPlaceOrder>(.//h6)[9]";
	 public static String placeOrderButton="PlaceOrderButton>.//button[text()='Place Order']";
	 public static String checkout="CheckoutButton>.//button[text()='Secure Checkout']";
	 public static String guest="ContinueGuestButton>.//button[text()='Continue as Guest']";
	 public static String firstName="FirstNameField>.//input[@name='firstName']";
	 public static String lastName="LastNameField>.//input[@name='lastName']";
	 public static String email="EmailField>.//input[@name='email']";
	 public static String phone ="PhoneField>.//input[@name='phone']";
	 public static String company ="CompanyField>.//input[@name='company']";
	 public static String addressCheckbox ="AddressCheckBox>(.//label)[10]";
	 public static String addressCheckboxBeforeGoogleAddress ="AddressCheckBox>(//label)[8]";
	 public static String addressCheckboxAfterGoogleAddress ="AddressCheckBox>(//label)[9]";
	 public static String address1 ="Address1Field>.//input[@name='addressLookup']";
	 public static String address ="AddressField>.//input[@name='address']";
	 public static String addressLookup ="AddressField>.//input[@name='addressLookup']";
	 public static String suite ="AptSuiteField>.//input[@name='aptSuite']";
	 public static String city ="CityField>.//input[@name='city']";
	 public static String state ="StateDropdown>.//select[@class='select']";
	 public static String zipcode ="ZipCodeField>.//input[@name='zipcode']";
	 public static String nextStep ="NextStepButton>.//button[text()='Next Step']";
	 public static String creditCard ="CreditCard>.//div[text()='Pay Now with Credit Card']";
	 public static String cardNumber ="CardNumberField>.//input[@name='card_number']";
	 public static String nameOnCard ="NameOnCardField>.//input[@name='fullName']";
	 public static String expiryMonth ="ExpiryMonthField>.//input[@name='expiration-mm']";
	 public static String expiryYear ="ExpiryYearField>.//input[@name='expiration-yy']";
	 public static String expiryCVV ="ExpiryCVVField>.//input[@name='cvv']";
	 //public static String billingAddressCheckbox ="BillingAddressCheckBox>.//input[@name='billingisunique']";
	 public static String sameAsShippingAddress ="SameAsShippingAddressCheckBox>.//label[text()='Same as shipping address.']";
	 public static String alertPopup ="AlertPopup>.//button[text()='Okay']";
	 public static String editButton ="EditButton>.//div[text()='Edit']";
	 public static String editButton1 ="EditButton>(.//div[text()='Edit'])[1]";
	 public static String editButton2 ="EditButton>(.//div[text()='Edit'])[2]";
	 public static String editIcon ="EditIcon>.//i[@class='icon icon-edit']";
	 public static String requiredError ="RequiredErrorMessage>.//p[text()='required']";
	 public static String orderNo ="OrderNumber>.//h6/span";
	 public static String sofaAfterOrder ="SofaAfterOrdering>.//li/strong";
	 public static String grandTotal ="GrandTotal>(.//span/strong)[2]";
	 public static String emailMeOrderDetails ="EmailMeOrderDetailsButton>.//button[text()='Email me order details!']";
	 public static String recieveEmailButton ="RecieveEmailButton>.//button[text()='You should recieve an email from us shortly']";
	 public static String billingFirstName ="FirstNameFiledInBilling>.//input[@name='billingFirstName']";
	 public static String billingLastName ="LastNameFiledInBilling>.//input[@name='billingLastName']";
	 public static String billingAddress1 ="AddressFiledInBilling>.//input[@name='billingAddressLookup']";
	 public static String billingAddress ="AddressFiledInBilling>.//input[@name='billingAddress']";
	 public static String billingSuite ="SuiteFiledInBilling>.//input[@name='billingAptSuite']";
	 public static String billingCity ="CityFiledInBilling>.//input[@name='billingCity']";
	 public static String billingState ="StateFiledInBilling>.//select[@name='billingState']";
	 public static String billingZip ="ZipFiledInBilling>.//input[@name='billingZip']";
	 public static String dontSeeMyAddress ="DontSeeMyaddressCheckBox>(.//label)[14]";
	 public static String dontSeeMyAddressBeforeGoogleAddress ="DontSeeMyaddressCheckBox>(.//label)[12]";
	 public static String dontSeeMyAddressAfterGoogleAddress ="DontSeeMyaddressCheckBox>(.//label)[13]";
	 public static String googleLookup ="GoogleLookup>.//div[@class='pac-item']";
	 public static String shippingUnchecked ="UncheckedShippingCheckbox>(.//input[@data-checked='false'])[2]";
	 public static String shippingChecked ="CheckedShippingCheckbox>.//input[@data-checked='true']";
	 public static String billingChecked ="CheckedBillingCheckbox>.//input[@data-checked='true']";
	 public static String userName ="UserNameField>(.//input[@name='email'])[2]";
	 public static String password ="PasswordField>(.//input[@name='password'])[2]";
	 public static String rememberMe ="RememberMeCheckBox>(.//label)[8]";
	 public static String login ="LoginButton>.//button[text()='Log In']";
	
	}